name: test

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - test

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Organize files
      run: |
        echo "prerelease_symbol=true" >> ${GITHUB_ENV}
        if [[ "${{ github.event_name }}" == 'repository_dispatch' ]]; then
          echo "prerelease_symbol=false" >> ${GITHUB_ENV}
        fi

    - name: test
      run: |
        echo ${{ env.prerelease_symbol }}
