name: TEST

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - test

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Show system
      run: |
        echo -e "💬 Server information \n"
        echo -e "💻 Server running on Ubuntu: [ Release: $(cat /etc/os-release | grep VERSION_CODENAME | cut -d '=' -f2) / Host: `arch` ] \n"
        echo -e "🧮 Server CPU configuration information: \n$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo -e "💾 Server memory usage: \n$(free -h) \n"
        echo -e "🗃️ Server space usag: \n$(df -hT ${GITHUB_WORKSPACE}) \n"

    - name: Package firmware
      uses: ffuqiangg/openwrt_packit@master
      env:
        SCRIPT_REPO_URL: ffuqiangg/openwrt_packit
        OPENWRT_ARMVIRT: 'https://github.com/ffuqiangg/openwrt_packit/releases/download/test/immortalwrt-armvirt-64-default-rootfs.tar.gz'
        PACKAGE_SOC: s905d
        KERNEL_REPO_URL: ffuqiangg/amlogic-s9xxx-armbian
        KERNEL_VERSION_NAME: 5.4.203
        KERNEL_AUTO_LATEST: false
        GZIP_IMGS: 'zip'
        SCRIPT_S905D: mk_immortalwrt_18.06_k5.4_n1.sh
        OPENWRT_VER: '18.06 k5.4'
        SFE_FLOW: 0
        ENABLE_WIFI_K504: 0
        ENABLE_WIFI_K510: 0
        DISTRIB_REVISION: '18.06 k5.4'
        DISTRIB_DESCRIPTION: ImmortalWrt
        BUILD_DATE: '2024.10.30'

    - name: Upload firmware to release
      uses: ncipollo/release-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: '2024.10.30'
        allowUpdates: true
        replacesArtifacts: true
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/N1-ImmortalWrt-18.06-K5.4-2024.10.30.zip

    - name: Telegram notification
      if: github.event_name == 'repository_dispatch'
      run: |
        firmware_num="$(curl -fsSL https://github.com/ffuqiangg/build_openwrt/releases/expanded_assets/2024.10.30 | grep -oE "N1-.*.zip" | sort -u | wc -l)"
        MSG="
        *${{ env.build_date }}* 固件编译完成
        https://github.com/ffuqiangg/build\_openwrt/releases/tag/2024.10.30
        "
        if [[ "${firmware_num}" == 5 ]]; then
          curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_TO }}&text=${MSG}&parse_mode=MarkDown&disable_web_page_preview=true"
        fi
